Facultad de Contaduria Pública y Administración / UANL / Análisis de Datos 2024 / Profesor MSI Marco Trejo

## <span style='font-family:Times New Roman'><font color="darkblue"> Tarea 1 Operaciones Básicas con Pandas</font> </span>

 Importar, Crear y editar un Dataset simple para operaciones básicas como filtrado, agrupación y ordenamiento de datos.

1.- Importar librerias

In [10]:
#importa las siguientes librerias: pandas y numpy y crea las variables respectivas: pd y np y presiona control + enter para ejecutar
#import (nombre de libreria) (variable)
import pandas as pd
import numpy as np


2.- Declara y Crea 6 series

In [37]:
#utilizando la variable pd crea una serie llamada nombre y agrega 5 valores de texto
nombre = pd.Series(['Marco','Juan','Adrian','Carlos','Gisel'])

#utilizando la variable pd crea una serie llamada apellido_paterno y agrega 5 valores de texto
apellido_paterno = pd.Series(['Perez','Martinez','Rios','Garza','Villarreal'])

#utilizando la variable pd crea una serie llamada apellido_materno y agrega 5 valores de texto
apellido_materno = pd.Series(['Sanchez','Alba','Hernandez','Hinojosa','Leal'])

#utilizando la variable pd crea una serie llamada salario y agrega 5 valores numericos enteros
salario = pd.Series([10000,12000,14000,16000,10000])

#utilizando la variable pd crea una serie llamada telefono y agrega 5 valores numericos enteros
telefono = pd.Series([8180507078,8180404890,8180568049,8120608978,8180012015])

#utilizando la variable pd crea una serie llamada numEmpleadoID y agrega 5 valores numericos enteros
numEmpleadoID = pd.Series([10,11,12,13,14])

# presiona control + enter para ejecutar

Visualiza la Serie nombre

In [12]:
# coloca la serie nombre y presiona control + enter
nombre

0     Marco
1      Juan
2    Adrian
3    Carlos
4     Gisel
dtype: object

Visualiza la Serie apellido paterno

In [13]:
# coloca la serie apellido_paterno y presiona control + enter
apellido_paterno

0         Perez
1      Martinez
2          Rios
3         Garza
4    Villarreal
dtype: object

Visualiza la Serie apellido materno

In [14]:
# coloca la serie apellido_materno y presiona control + enter
apellido_materno

0      Sanchez
1         Alba
2    Hernandez
3     Hinojosa
4         Leal
dtype: object

Visualiza la Serie salario

In [15]:
# coloca la serie salario y presiona control + enter
salario

0    10000
1    12000
2    14000
3    16000
4    18000
dtype: int64

Visualiza la Serie telefono

In [17]:
# coloca la serie telefono y presiona control + enter
telefono

0    8180507078
1    8180404890
2    8180568049
3    8120608978
4    8180012015
dtype: int64

Visualiza la Serie NumEmpleadoID

In [18]:
# coloca la serie numEmpleadoID y presiona control + enter
numEmpleadoID

0    10
1    11
2    12
3    13
4    14
dtype: int64

Visualiza solo los valores (datos) del objeto **Series**:

In [20]:
# coloca la serie nombre separada por un punto . y la palabra values y presiona control + enter
nombre.values

array(['Marco', 'Juan', 'Adrian', 'Carlos', 'Gisel'], dtype=object)

In [25]:
# coloca la serie apellido_paterno separada por un punto . y la palabra values y presiona control + enter
apellido_paterno.values

array(['Perez', 'Martinez', 'Rios', 'Garza', 'Villarreal'], dtype=object)

In [24]:
# coloca la serie apellido_materno separada por un punto . y la palabra values y presiona control + enter
apellido_materno.values

array(['Sanchez', 'Alba', 'Hernandez', 'Hinojosa', 'Leal'], dtype=object)

In [23]:
# coloca la serie salario separada por un punto . y la palabra values y presiona control + enter
salario.values

array([10000, 12000, 14000, 16000, 18000])

In [22]:
# coloca la serie telefono separada por un punto . y la palabra values y presiona control + enter
telefono.values

array([8180507078, 8180404890, 8180568049, 8120608978, 8180012015])

In [21]:
# coloca la serie apellido_paterno separada por un punto . y la palabra values y presiona control + enter
numEmpleadoID.values

array([10, 11, 12, 13, 14])

Visualiza solo los indices (index) del objeto **Series**:

In [26]:
# coloca la serie nombre separada por un punto . y index.tolist() y presiona control + enter
nombre.index.tolist()

[0, 1, 2, 3, 4]

In [27]:
# coloca la serie apellido_paterno separada por un punto . y index.tolist() y presiona control + enter
apellido_paterno.index.tolist()

[0, 1, 2, 3, 4]

In [28]:
# coloca la serie apellido_materno separada por un punto . y index.tolist() y presiona control + enter
apellido_materno.index.tolist()

[0, 1, 2, 3, 4]

In [29]:
# coloca la serie salario separada por un punto . y index.tolist() y presiona control + enter
apellido_paterno.index.tolist()

[0, 1, 2, 3, 4]

In [30]:
# coloca la serie telefono separada por un punto . y index.tolist() y presiona control + enter
apellido_paterno.index.tolist()

[0, 1, 2, 3, 4]

In [31]:
# coloca la serie numEmpleadoID separada por un punto . y index.tolist() y presiona control + enter
numEmpleadoID.index.tolist()

[0, 1, 2, 3, 4]

Encontrar el valor máximo y mínimo del objeto **Series**: salario

In [32]:
# coloca la serie salario separada por un punto . y la palabra max() y presiona control + enter
salario.max()

18000

In [33]:
# coloca la serie salario separada por un punto . y la palabra min() y presiona control + enter
salario.min()

10000

Encontrar las medidas de tendencia central: media, mediana y moda (mean,median,mode) para el objeto salario **Series**: salario

In [34]:
# coloca la serie salario separada por un punto . y la palabra mean()
salario.mean()

14000.0

In [35]:
# coloca la serie salario separada por un punto . y la palabra median()
salario.median()

14000.0

In [38]:
# coloca la serie salario separada por un punto . y la palabra mode()
salario.mode()

0    10000
dtype: int64

Crear un objeto **DataFrame** a partir de listas de Python:

In [40]:
# utilizaremos 5 de las listas ya creadas anteriormenete comoo Series: nombre, apellido_paterno, apellido_materno, salario, numEmpleadoID


# crea el objeto datos_de_los_empleados agregando las listas creadas y su nombre de columna: Nombre, Apellido Paterno, Apellido Materno, Salario, Num. Tel, EmpleadoID
datos_de_los_empleados = {'Nombre': nombre, 'Apellido Paterno': apellido_paterno, 'Apellido Materno': apellido_materno, 'Salario': salario, 'Num. Tel':telefono, 'EmpleadoID':numEmpleadoID}

# crea el objeto llamado: demp .... que sea de tipo DataFrame ejemplo: variable = pd.DataFrame(datos_de_los_empleados)
demp = pd.DataFrame(datos_de_los_empleados)


In [41]:
# coloca el nombre del objeto demp y presiona control + enter
demp

Nombre Apellido Paterno Apellido Materno  Salario    Num. Tel  EmpleadoID
0   Marco            Perez          Sanchez    10000  8180507078          10
1    Juan         Martinez             Alba    12000  8180404890          11
2  Adrian             Rios        Hernandez    14000  8180568049          12
3  Carlos            Garza         Hinojosa    16000  8120608978          13
4   Gisel       Villarreal             Leal    10000  8180012015          14

Visualiza los indices del DataFrame

In [45]:
#coloca el id del DataFrame demp separado por un punto . y la palabra index,tolist()

demp.index.tolist()

[0, 1, 2, 3, 4]

Encuentra el valor máximo y mínimo en un objeto **DataFrame**:

In [47]:
# coloca el objeto DataFrama llamado demp separado por un punto . y la palabra min()

demp.min()

Nombre                  Adrian
Apellido Paterno         Garza
Apellido Materno          Alba
Salario                  10000
Num. Tel            8120608978
EmpleadoID                  10
dtype: object

##<font color=firebrick>4 Pasos para Importar datos de archivos de Excel con pandas </font>

Primero: Colocar el archivo CSV en nuestro Google drive raiz

In [ ]:
# Primero debemos colocar el archivo CSV de nuestra preferencia en nuestro Google Drive puedes descargar usar cualquier fuente CSV de la pagina https://www.tableau.com/es-es/blog/public-data-sets-102221



Segundo: Asignar la localización del archivo a una variable. Esta represantación de la localización del archivo es a lo que llamamos filepath.

In [51]:
# Segundo debemos conectarnos a nuestro drive, ya sea en la barra lateral izquierda o con los comandos siguientes.
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


Tercero: Después nos debemos situar en la dirección donte esta el archivo o en su defecto darle el path completo de la localización del archivo

In [65]:
# Tercero: Se importa la librería pandas, para el manejo de datos.
# Se le asigna el alias "pd", que es el estándar de
# codificación de la comunidad.

import pandas as pd

# Como los datos están en un archivo CSV, en lugar del nombre de
# archivo se utiliza la URL para acceso raw a los datos,
# que es lo mismo que leer un archivo que tenemos físicamente
# en nuestro equipo. Se declara una variable para almacenar la URL.

# Crear la variable para almacenar el archivo CSV en este caso datos_naciones_csv
datos_naciones_csv = '/content/drive/MyDrive/nations.csv'

# Se cargan los datos del archivo en la variable "datos_naciones_csv" a un
# DataFrame de pandas llamado "naciones", usando la función
# pd.read_csv(), usando como nombre de archivo la variable
# que almacena la URL para acceder a los datos.

naciones = pd.read_csv(datos_naciones_csv, encoding='latin-1')

Cuarto: Visualizar los datos del DataFrame generado desde el CSV

In [64]:
# Cuarto: visualizar datos del DataFrame colocando el nombre del dataframe
naciones

Unnamed: 0          country   region           gdp     school  \
0             1          Algeria   Africa   7300.399902   6.716667   
1             2            Benin   Africa   1338.800049   3.100000   
2             3         Botswana   Africa  12307.400390   8.600000   
3             4     Burkina Faso   Africa   1063.400024   1.300000   
4             5          Burundi   Africa    349.200012   2.483333   
..          ...              ...      ...           ...        ...   
189         190            Samoa  Oceania   4012.600098  10.300000   
190         191  Solomon Islands  Oceania   2249.199951   4.500000   
191         192            Tonga  Oceania   4072.199951  10.133333   
192         193           Tuvalu  Oceania           NaN        NaN   
193         194          Vanuatu  Oceania   3809.800049   6.700000   

         adfert  chldmort       life       pop      urban  femlab   literacy  \
0      7.300000     34.75  72.316666  34172236  64.933334  0.4522  72.599998   
1    111.699997    122.75  54.733334   8237634  41.000000  0.8482  41.700001   
2     52.099998     60.25  52.250000   1941233  59.250000  0.8870  84.099998   
3    124.800003    170.50  53.783333  15308383  23.583334  0.8584  23.600000   
4     18.600000    168.50  48.866665   7821783  10.250000  1.0344  66.599998   
..          ...       ...        ...       ...        ...     ...        ...   
189   28.299999     26.75  71.533333    181600  20.666668  0.5010  98.800003   
190   70.300003     36.00  66.500000    503617  17.766666  0.4858        NaN   
191   22.299999     19.25  71.833336    102550  23.266666  0.7150  99.000000   
192   23.299999     36.50  66.033333      9767  49.233334     NaN        NaN   
193   54.000000     17.75  69.966667    225317  24.500000  0.8988  82.000000   

       co2       gini  
0    15.00        NaN  
1     1.20        NaN  
2     9.20        NaN  
3     0.20        NaN  
4     0.10  33.299999  
..     ...        ...  
189   3.10        NaN  
190   1.40        NaN  
191   4.85        NaN  
192    NaN        NaN  
193   1.50        NaN  

[194 rows x 14 columns]

##<font color=firebrick>Ahora es tu turno sigue los pasos del 1 al 4 para importar tu archivo CSV </font>

In [ ]:
# Primero debemos colocar el archivo CSV de nuestra preferencia en nuestro Google Drive puedes descargar usar cualquier fuente CSV de la pagina https://www.tableau.com/es-es/blog/public-data-sets-102221



In [ ]:
# Segundo debemos conectarnos a nuestro drive, ya sea en la barra lateral izquierda o con los comandos siguientes.
from google.colab import drive
drive.mount('/content/drive/')

In [ ]:
# Tercero: Se importa la librería pandas, para el manejo de datos.
# Se le asigna el alias "pd", que es el estándar de
# codificación de la comunidad.

import pandas as pd

# Como los datos están en un archivo CSV, en lugar del nombre de
# archivo se utiliza la URL para acceso raw a los datos,
# que es lo mismo que leer un archivo que tenemos físicamente
# en nuestro equipo. Se declara una variable para almacenar la URL.

# Crear la variable para almacenar el archivo CSV en este caso: ejemplos: datos_airline-safety_csv, fifa_countries_audience_csv
 datos_nombrevariable_csv = '/content/drive/MyDrive/nombre_archivo.csv'

# Se cargan los datos del archivo en la variable "datos_naciones_csv" a un
# DataFrame de pandas llamado "naciones", usando la función
# pd.read_csv(), usando como nombre de archivo la variable
# que almacena la URL para acceder a los datos.

variableDataFrame = pd.read_csv( datos_nombrevariable_csv, encoding='latin-1')

In [ ]:
# Cuarto: visualizar datos del DataFrame colocando el nombre del dataframe
variableDataFrame